name: test_delete
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  proste_bezier_curve: ^2.0.2
  curved_navigation_bar: ^1.0.3
  cloud_functions: ^4.6.0
  file_picker: ^8.0.0+1
  image_picker: ^1.0.6
  url_launcher: ^6.0.12
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.14.0
  firebase_core: ^2.16.1
  firebase_storage: ^11.5.6
  firebase_auth: ^4.6.5
  path: any
  google_sign_in: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^2.7.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # - lib/assets/baby.json
    - lib/assets/images/
    - lib/assets/icons/
